import {Dimensions} from 'react-native';

const React = require('react-native');
const {width: WIDTH, height: height} = Dimensions.get('window');
const {StyleSheet} = React;
import {Fonts} from '../utils/Fonts';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import * as colors from '../style/Common/ColorsStyle';
module.exports = StyleSheet.create({
  container: {
    //flex: 1,
    width: WIDTH,
    height: '100%',
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  searchView: {
    width: '86%',
    height: hp('6'),
    //backgroundColor: 'red',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: hp('1%'),
  },
  searchInput: {
    width: '80%',
    height: hp('6'),
    backgroundColor: '#F6F6F6',
    borderRadius: 15,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  searchIcon: {
    width: wp('3.5'),
    height: hp('2.5'),
    marginLeft: '3%',
  },
  TxtInput: {
    width: '80%',
    height: hp('7'),
    fontSize: hp(2),
    // fontWeight: 'bold',
    // backgroundColor: 'red',
  },
  filterBtn: {
    width: wp('11'),
    height: hp('6'),
    backgroundColor: '#1ED18C',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: '5%'
   
  },
  filterIcon: {
    width: 30,
    height: 20,
  },
  titleTxt: {
    fontSize: hp('2.5'),
    fontFamily: Fonts.PoppinsBold,
    color: 'black',
    fontWeight: 'bold',
    //textAlign: 'center',
  },
  titleView: {
    width: '90%',
    height: hp('5'),
    marginTop:hp('2'),
    alignSelf: 'flex-start',
    marginLeft:wp('8')
  },
  footerCardView: {
    width: '90%',
    height: hp('15'),
    backgroundColor: 'white',
    //marginLeft: 10,
    borderRadius: 15,
    alignItems: 'center',
    //shadowColor: 'red',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.6,
    shadowRadius: 1,
    elevation: 2,
    margin: 8,
    marginLeft: '5%',
    marginTop: hp('2'),
    //justifyContent: 'center',
    // borderColor: 'rgba(44, 130, 201, 1)',
    // borderWidth: 0.5,
    flexDirection: 'row',
    // justifyContent: 'center',
  },
  footerCardView2: {
    width: '90%',
    paddingTop: 20,
    height: hp('28'),
    backgroundColor: 'white',
    //marginLeft: 10,
    borderRadius: 15,
    alignItems: 'center',
    //shadowColor: 'red',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.6,
    shadowRadius: 1,
    elevation: 2,
    margin: 8,
    marginLeft: '5%',
    marginTop: hp('6'),
    //justifyContent: 'center',
    // borderColor: 'rgba(44, 130, 201, 1)',
    // borderWidth: 0.5,
    //flexDirection: 'row',
    // justifyContent: 'center',
  },
  cardSubMainTxt: {
    fontSize: hp('1.5'),
    fontFamily: Fonts.PoppinsSemiBold,
    color: 'gray',
    //marginLeft: '2%',
  },
  cardSubTxt: {
    fontSize: hp('1.6'),
    fontFamily: Fonts.PoppinsSemiBold,
    color: 'gray',
    marginLeft: '2%',
  },
  cardImg: {
    // width: wp('15'),
    // height: hp('10'),
    width: 90,
    height: 90,
    // borderRadius: 10,
    //resizeMethod: 'cover',
  },
  cardSubImg: {
    // width: wp('15'),
    // height: hp('10'),
    width: 60,
    height: 60,
  },
  headerView: {
    width: '85%',
    height: hp('5'),
    //backgroundColor: 'red',
    marginTop: hp('5%'),
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
  },
  drawerIcon: {
    width: 25,
    height: 18,
  },
  cartIcon: {
    width: 35,
    height: 25,
  },
  removeIcon: {
    width: 25,
    height: 25,
    //position: 'absolute',
    //marginLeft: '5%',
  },
  removeIconView: {
    width: wp('12'),
    height: hp('15'),
    position: 'absolute',
    alignItems: 'flex-end',
    justifyContent: 'flex-start',
    //backgroundColor: 'yellow',
    marginLeft: wp('80'),
  },
  cardImgView: {
    width: '30%',
    //backgroundColor: 'red',
    height: hp('15'),
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardTxtView: {
    width: '70%',
    //backgroundColor: 'yellow',
    height: hp('15'),
    alignItems: 'flex-start',
    justifyContent: 'center',
    marginLeft: wp('1'),
  },
  cardTxtView1: {
    width: '90%',
    height: hp('3'),
    //backgroundColor: 'red',
    justifyContent: 'center',
  },
  cardTxtView2: {
    width: '100%',
    height: hp('5'),
    //backgroundColor: 'green',
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
  },
  numericView: {
    width: '50%',
    backgroundColor: 'white',
  },
  cardTxtView3: {
    width: '50%',
    //backgroundColor: 'white',
    height: hp('5'),
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerBtn: {
    width: '90%',
    height: hp('7'),
    backgroundColor: 'rgba(44, 130, 201, 1)',
    marginTop: hp('3'),
    alignItems: 'center',
    marginLeft: wp('5'),
    justifyContent: 'center',
    borderRadius: 10,
  },
  BtnTxt: {
    fontSize: hp('2.1'),
    fontFamily: Fonts.PoppinsSemiBold,
    marginTop: '1%',
    color: 'white',
    //textAlign: 'center',
  },
  footerTxtView2: {
    width: '90%',
    height: hp('4'),
    //backgroundColor: 'red',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  fMainTxt: {
    fontSize: hp('1.6'),
    fontFamily: Fonts.PoppinsSemiBold,
    color: 'black',
    //marginLeft: '2%',
  },
  fMainTxt2: {
    fontSize: hp('1.6'),
    fontFamily: Fonts.PoppinsSemiBold,
    color: 'gray',
    //marginLeft: '2%',
  },
  oderTotalView: {
    width: '90%',
    height: hp('4'),
    //backgroundColor: 'red',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp('2'),
  },
  OMainTxt: {
    fontSize: hp('2'),
    fontFamily: Fonts.PoppinsBold,
    color: 'black',
    //marginLeft: '2%',
  },
  OMainTxt2: {
    fontSize: hp('2'),
    fontFamily: Fonts.PoppinsBold,
    color: 'rgba(44, 130, 201, 1)',
    //marginLeft: '2%',
  },
  noItemTxt: {
    fontSize: hp('3'),
    fontFamily: Fonts.PoppinsBold,
    color: 'black',
    //marginLeft: '2%',
  },
  noItemView: {
    width: '80%',
    height: '70%',
    //backgroundColor: 'red',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
