import { StyleSheet } from 'react-native';
import * as colors from '../style/Common/ColorsStyle';

module.exports = StyleSheet.create({
  main: {
    width: '92%',
    padding: 5,
    backgroundColor: '#fff',
    borderRadius: 15,
    elevation: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    alignSelf: 'center',
    marginTop: 10,
  },
  topView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: 60,
  },
  firstRow: {
    width: '40%',
    height: '100%',
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingLeft: 10,
  },
  secondRow: {
    width: '40%',
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingLeft: 10,
  },
  arrowView: {
    width: '20%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  arrowBtn: {
    width: 30,
    height: 30,
    // backgroundColor: colors.primaryColor,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 30,
  },
  midView: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  midRowView: {
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginBottom: 5,
  },
  midFirstRow: {
    width: '40%',
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingLeft: 10,
  },
  midSecondRow: {
    width: '60%',
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingLeft: 10,
  },
  addressView: {
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginTop: 5,
    width: '100%',
  },
  addressRowView: {
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    paddingLeft: 10,
    width: '100%',
    flexDirection: 'row',
  },
  addressRow: {
    width: '40%',
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  addressRowData: { width: '60%', alignItems: 'flex-start' },
  bottomView: {
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginTop: 10,
    width: '100%',
  },
  bottomRowView: {
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    paddingLeft: 10,
    width: '100%',
    flexDirection: 'row',
  },
  bottomRow: {
    width: '40%',
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  bottomRowData: {
    width: '60%',
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  deliveryOptionView: {
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginTop: 0,
    width: '100%',
  },
  deliveryOptionRowView: {
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingLeft: 10,
    width: '100%',
    flexDirection: 'row',
  },
  deliveryOptionRow: {
    width: '40%',
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  deliveryOptionRowData: {
    width: '60%',
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  UnavailableItemView: { width: '100%', flexDirection: 'row', paddingLeft: 10 },
  UnavailableItemRow: {
    width: '40%',
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  UnavailableItemRowData: {
    width: '60%',
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
});
