import { Dimensions, Platform, PixelRatio } from "react-native";

const React = require("react-native");
const { width: WIDTH, height: height } = Dimensions.get("window");
//const { StyleSheet } = React;
import { Fonts } from "../utils/Fonts";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";
import * as colors from '../style/Common/ColorsStyle';
import StyleSheet from "react-native-media-query";
const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get("window");

// based on iphone 5s's scale
const scale = SCREEN_WIDTH / 320;

export function normalize(size) {
  const newSize = size * scale;
  if (Platform.OS === "ios") {
    return Math.round(PixelRatio.roundToNearestPixel(newSize));
  } else {
    return Math.round(PixelRatio.roundToNearestPixel(newSize)) - 2;
  }
}

module.exports = StyleSheet.create({
  container: {
    //flex: 1,
    width: WIDTH,
    height: '100%',
    backgroundColor: '#F9F9F9',
    // alignItems: 'center',
    justifyContent: 'flex-start',
  },
  searchView: {
    width: '93%',
    height: hp('05'),
    // backgroundColor: 'red',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: hp('1%'),
    marginBottom: hp('2%'),
  },
  applyView: {
    width: '100%',
    height: hp('6'),
    marginLeft: wp('1'),
    //backgroundColor: 'red',
    flexDirection: 'row',

    alignItems: 'center',
    marginTop: hp('1%'),
  },
  preseasonView: {
width: '50%',
    height: hp("2.3"),
    // alignItems: "center",
    justifyContent: "center",
    // marginTop: hp("1"),
    backgroundColor: colors.primaryColor,
    // marginBottom: hp("1"),
    borderRadius: 5,
    alignSelf: "center",
  },
  preseasonTxt: {
    fontSize: hp("1.5"),
    // fontFamily: Fonts.PoppinsBold,
    color: "white",
    textAlign: 'center',
  },
  searchInput: {
    width: '87%',
    height: hp('5'),
    backgroundColor: 'white',
    borderRadius: hp('1'),
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    borderWidth: hp('0.1'),
    borderColor: '#e6e6e6',
  },
  applyInput: {
    width: '60%',
    height: hp('5'),
    backgroundColor: 'white',
    borderColor: '#F6F6F6',
    borderWidth: 3,
    borderRadius: 15,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  searchIcon: {
    width: wp('3.5'),
    height: hp('2.5'),
    marginLeft: '3%',
  },

  TxtInput: {
    width: '80%',
    height: hp('7'),
    fontSize: hp(1.7),
    color:'black'
    // fontWeight: 'bold',
    // backgroundColor: 'red',
  },
  filterBtn: {
    width: wp('9'),
    height: hp('5'),
    backgroundColor: '#1ED18C',
    borderRadius: hp('1'),
    alignItems: 'center',
    justifyContent: 'center',
  },
  applyBtn: {
    width: wp('12'),
    height: hp('5'),
    backgroundColor: 'white',
    borderWidth: 3,
    borderColor: '#1ED18C',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: wp('2'),
  },
  filterIcon: {
    width: wp('5'),
    height: hp('2.5'),
  },
  titleTxt: {
    fontSize: hp('2.2'),
    // fontFamily: Fonts.PoppinsBold,
    color: 'black',
    fontWeight: 'bold',
    marginLeft: wp('3'),
    //textAlign: 'center',
  },
  titleView: {
    width: '100%',
    height: hp('4'),
    // marginTop: hp('2'),


  },
  footerCardView: {
    width: '94%',
    height: hp('7'),
    backgroundColor: 'white',
    borderRadius: wp('1'),
    alignItems: 'center',
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 1,
    marginBottom: hp('1.3'),
    alignSelf: 'center',
    //justifyContent: 'center',
    // borderColor: 'rgba(44, 130, 201, 1)',
    // borderWidth: 0.5,
    flexDirection: 'row',
    '@media (max-width: 1600px) and (min-width: 450px)': {
      height: hp('7'),
      borderRadius: wp('1'),
    },
    '@media (max-width: 450px)': {
      height: hp('13'),
      borderRadius: wp('2'),
    },
  },
  footerCardView2: {
    width: '90%',
    paddingTop: 20,
    height: hp('28'),
    backgroundColor: 'white',
    //marginLeft: 10,
    borderRadius: 15,
    alignItems: 'center',
    //shadowColor: 'red',
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 1,
    margin: 8,
    marginLeft: '5%',
    marginTop: hp('6'),
    //justifyContent: 'center',
    // borderColor: 'rgba(44, 130, 201, 1)',
    // borderWidth: 0.5,
    //flexDirection: 'row',
    // justifyContent: 'center',
  },
  cardSubMainTxt: {
    fontSize: hp('1.2'),
    // fontFamily: Fonts.PoppinsBold,
    color: colors.fourthiaryColor,
    marginLeft: '2%',
    '@media (max-width: 1600px) and (min-width: 450px)': {},
    '@media (max-width: 450px)': {
      fontSize: hp('1.5'),
    },
  },
  cardSubMainTxt5: {
    fontSize: hp('1.2'),
    // fontFamily: Fonts.PoppinsBold,
    color: '#1ED18C',
    '@media (max-width: 1600px) and (min-width: 450px)': {},
    '@media (max-width: 450px)': {
      marginLeft: '2%',
      fontSize: hp('1.5'),
    },
  },
  savingsText: {
    fontSize: wp('2'),
    // fontFamily: Fonts.PoppinsBold,
    color: 'gray',
    marginLeft: wp('2'),
  },
  subcontains: {
    flexDirection: 'row',
    '@media (max-width: 1600px) and (min-width: 450px)': {
      flexDirection: 'row',
    },
    '@media (max-width: 450px)': {
      flexDirection: 'row',
    },
  },
  savingssubText: {
    fontSize: wp('2'),
    // fontFamily: Fonts.PoppinsBold,
    color: 'black',
  },
  cardTxt: {
    fontSize: hp('1.3'),
    // fontFamily: Fonts.PoppinsBold,
    color: 'black',
    fontWeight: 'bold',
    marginLeft: wp('1'),
    '@media (max-width: 1600px) and (min-width: 450px)': {
      fontSize: hp('1'),
      marginBottom: wp('0.4'),
    },
    '@media (max-width: 450px)': {
      fontSize: hp('1.5'),
    },
  },
  cardTxt2: {
    fontSize: wp('2'),
    // fontFamily: Fonts.PoppinsBold,
    color: 'black',
    fontWeight: 'bold',
    marginLeft: wp('2'),
  },
  cardSubTxt: {
    fontSize: wp('2'),
    // fontFamily: Fonts.PoppinsSemiBold,
    color: 'gray',
    marginLeft: '2%',
  },
  cardImg: {
    flex: 1,
    aspectRatio: 0.3,
    resizeMode: 'contain',
    // borderRadius: 1,
    // width: '40%',
    // height: '50%',
    // // width: wp('2'),
    // // height: hp('2'),
    // borderRadius: 10,
    // //resizeMethod: 'cover',
    '@media (max-width: 450px)': {
      aspectRatio: 0.4,
    },
  },
  cardSubImg: {
    // width: wp('15'),
    // height: hp('10'),
    width: 60,
    height: 60,
  },
  headerView: {
    width: '85%',
    height: hp('5'),
    //backgroundColor: 'red',
    marginTop: hp('5%'),
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
  },
  drawerIcon: {
    width: 25,
    height: 18,
  },
  cartIcon: {
    width: 35,
    height: 25,
  },
  removeIcon: {
    width: 25,
    height: 25,
    //position: 'absolute',
    //marginLeft: '5%',
  },
  removeIconView: {
    width: wp('12'),
    height: hp('15'),
    position: 'absolute',
    alignItems: 'flex-end',
    justifyContent: 'flex-start',
    //backgroundColor: 'yellow',
    marginLeft: wp('80'),
  },
  cardImgView: {
    width: '30%',
    //backgroundColor: 'red',
    marginLeft: wp('-3'),
    height: hp('15'),
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardTxtViewPrice: {},
  cardTxtView: {
    width: '65%',
    height: hp('8'),
    alignItems: 'flex-start',
    justifyContent: 'center',
    marginLeft: wp('1'),
    '@media (max-width: 1600px) and (min-width: 450px)': {
      width: '70%',

    },
    '@media (max-width: 450px)': {
      width: '65%',
      height: hp('6'),
      marginTop: hp('1'),
    },
  },
  cardTxtView1: {
    width: '90%',
    height: hp('3'),
    //backgroundColor: 'red',
    justifyContent: 'center',
  },
  totalTextView: {
    width: '100%',
    height: hp('3'),
    marginTop: hp('3'),
    //backgroundColor: 'red',
    flexDirection: 'row',
  },
  savingsTextView: {
    width: '100%',
    height: hp('3'),
    flexDirection: 'row',
    //backgroundColor: 'red',
    // justifyContent: 'center',
  },
  cardTxtView2: {
    width: '100%',
    height: hp('5'),
    //backgroundColor: 'green',
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
  },
  numericView: {
    width: '75%',
    alignItems: 'center',
    justifyContent: 'center',
    height: hp('4'),
    alignSelf: 'center',
    backgroundColor: 'white',
    borderWidth: hp('0.1'),
    borderColor: '#e6e6e6',
    borderRadius: hp('1'),
  },
  input: {
    fontSize: hp('1.5'),
    textAlign: 'center',
    width: '80%',
    height: hp('5'),
    color:'gray'
    // backgroundColor: 'red',
    // fontWeight: 'bold',
    // backgroundColor: 'red',
  },
  cardTxtView3: {
    width: '50%',
    //backgroundColor: 'white',
    height: hp('5'),
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerBtn: {
    width: '90%',
    height: hp('7'),
    backgroundColor: 'rgba(44, 130, 201, 1)',
    marginTop: hp('3'),
    alignItems: 'center',
    marginLeft: wp('5'),
    justifyContent: 'center',
    borderRadius: 10,
  },
  BtnTxt: {
    fontSize: wp('2'),
    // fontFamily: Fonts.PoppinsSemiBold,
    marginTop: '1%',
    color: 'white',
    //textAlign: 'center',
  },
  footerTxtView2: {
    width: '90%',
    height: hp('4'),
    //backgroundColor: 'red',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  fMainTxt: {
    fontSize: hp('1.6'),
    // fontFamily: Fonts.PoppinsSemiBold,
    color: 'black',
    //marginLeft: '2%',
  },
  fMainTxt2: {
    fontSize: hp('1.6'),
    // fontFamily: Fonts.PoppinsSemiBold,
    color: 'gray',
    //marginLeft: '2%',
  },
  oderTotalView: {
    width: '90%',
    height: hp('4'),
    //backgroundColor: 'red',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp('2'),
  },
  OMainTxt: {
    fontSize: hp('2'),
    // fontFamily: Fonts.PoppinsBold,
    color: 'black',
    //marginLeft: '2%',
  },
  OMainTxt2: {
    fontSize: hp('2'),
    // fontFamily: Fonts.PoppinsBold,
    color: 'rgba(44, 130, 201, 1)',
    //marginLeft: '2%',
  },
  noItemTxt: {
    fontSize: hp('3'),
    // fontFamily: Fonts.PoppinsBold,
    color: 'black',
    //marginLeft: '2%',
  },
  noItemView: {
    width: '80%',
    height: '70%',
    //backgroundColor: 'red',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cartItemTextView: {
    width: '100%',
    height: hp('6'),
    flexDirection: 'row',
    // justifyContent: "space-between",
    alignItems: 'center',

    '@media (max-width: 1600px) and (min-width: 450px)': {
      height: hp('6'),
      flexDirection: 'row',
    },
    '@media (max-width: 450px)': {
      height: hp('13'),
      flexDirection: 'column',
    },
  },
  cardView1: {
    flexDirection: 'row',
    alignItems: 'center',
    height: hp('6'),
    width: wp('55'),
    '@media (max-width: 1600px) and (min-width: 450px)': {
      width: wp('55'),
    },
    '@media (max-width: 450px)': {
      width: wp('94'),
    },
  },
  cardView2: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    height: hp('6'),
    width: wp('31'),
    '@media (max-width: 1600px) and (min-width: 450px)': {
      width: wp('31'),
    },
    '@media (max-width: 450px)': {
      width: wp('94'),
    },
  },

  AddView: {
    width: wp('12'),
    height: hp('6'),
    // alignItems: 'flex-end',
    justifyContent: 'center',
    marginLeft: wp('1'),
    flexDirection: 'row',
    '@media (max-width: 1600px) and (min-width: 450px)': {
      width: wp('12'),
    },
    '@media (max-width: 450px)': {
      width: wp('20'),
    },
  },
  PriceView: {
    width: wp('18'),
    height: hp('6'),
    alignItems: 'flex-end',
    justifyContent: 'center',
    '@media (max-width: 1600px) and (min-width: 450px)': {
      width: wp('18'),
    },
    '@media (max-width: 450px)': {
      width: wp('61'),
      alignItems: 'center',
    },
    //marginLeft: '5%'
  },
  searchresultView: {
    padding: 5,
    paddingLeft: 20,
    borderBottomWidth: 1,
    marginBottom: 1,
    borderColor: '#EEEEEE',
    justifyContent: 'center',
    '@media (max-width: 1600px) and (min-width: 450px)': {
      height: 55,
    },
    '@media (max-width: 450px)': {},
  },
  searchresultTxt: {
    color:'gray',
    '@media (max-width: 1600px) and (min-width: 450px)': {
      fontSize: hp('1.5'),
    },
    '@media (max-width: 450px)': {},
  },
  cardUnitPriceTxt: {
    fontSize: hp('1.3'),
    // fontFamily: Fonts.PoppinsBold,
    color: colors.fourthiaryColor,
    marginRight: wp('1'),
    '@media (max-width: 1600px) and (min-width: 450px)': {
      fontSize: hp('1.3'),
    },
    '@media (max-width: 450px)': {
      fontSize: hp('1.6'),
      textAlign: 'center',
    },
  },
  cardPriceTxt: {
    textAlign: 'right',
    fontSize: hp('2.2'),
    // fontFamily: Fonts.PoppinsBold,
    color: '#1ED18C',
    marginLeft: wp('1'),
    marginRight: wp('1'),
    fontWeight: 'bold',
    '@media (max-width: 1600px) and (min-width: 450px)': {
      fontSize: hp('1.6'),
    },
    '@media (max-width: 450px)': {
      fontSize: hp('1.7'),
      textAlign: 'center',
    },
  },
  totalTxt: {
    fontSize: hp('1.8'),
    // fontFamily: Fonts.PoppinsBold,
    color: '#1ED18C',
    marginLeft: wp('2'),
    fontWeight: 'bold',
  },
  DeleteView: {
    width: wp('8'),
    height: hp('6'),
    alignItems: 'center',
    justifyContent: 'center',
    '@media (max-width: 1600px) and (min-width: 450px)': {},
    '@media (max-width: 450px)': {
      alignItems: 'flex-end',
      marginLeft: wp('2'),
    },
  },
  delBtn: {
    alignItems: 'center',
    justifyContent: 'center',
    width: wp('6'),
    marginRight: wp('0.7'),
    height: hp('4'),
    backgroundColor: '#f8d1d9',
    borderRadius: wp('1'),
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 1,
    '@media (max-width: 1600px) and (min-width: 450px)': {
      width: wp('6'),
    },
    '@media (max-width: 450px)': {
      width: wp('9'),
    },
  },

  discountCode: {
    width: '49%',
    height: hp('13'),
    backgroundColor: 'white',
    borderRadius: 15,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.6,
    shadowRadius: 1,
    elevation: 2,
    // flexDirection: 'row',
    // justifyContent: 'space-around',
    alignItems: 'center',
  },
  basketRef: {
    width: '49%',
    height: hp('13'),
    backgroundColor: 'white',
    borderRadius: 15,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.6,
    shadowRadius: 1,
    elevation: 2,
    marginTop: wp('-46'),
    // flexDirection: 'row',
    // justifyContent: 'space-around',
    alignItems: 'flex-start',
  },
  basketTotal: {
    width: '49%',
    height: hp('20'),
    backgroundColor: 'white',
    borderRadius: 15,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.6,
    shadowRadius: 1,
    elevation: 2,
    marginLeft: wp('2'),
    // justifyContent: 'space-around',
    alignItems: 'flex-start',
  },

  AddToCartBtn: {
    width: wp('90') / 3,
    height: hp('4.5'),
    backgroundColor: '#1ED18C',
    borderRadius: wp('1.5'),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  printBtn: {
    width: wp('102') / 3,
    height: hp('4.5'),
    backgroundColor: '#1ED18C',
    borderRadius: wp('1.5'),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: wp('1'),
    backgroundColor: '#e8fcf4',
    borderWidth: hp('0.1'),
    borderColor: '#1ED18C',
  },
  clearListBtn: {
    width: wp('90') / 3,
    height: hp('4.5'),
    borderRadius: wp('1.5'),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: wp('1'),
    backgroundColor: '#fffcfc',
    borderWidth: hp('0.1'),
    borderColor: '#1ED18C',
  },

  mainBox: {
    width: wp('90'),
    height: hp('4'),
    backgroundColor: 'black',
    // borderRadius: 15,
    // flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    alignSelf: 'center',
    marginTop: hp('2%'),
    marginLeft: wp('-1.5%'),
  },

  checkoutTxt: {
    fontSize: hp('1.6'),
    color: 'white',
    // justifyContent: 'center',
    // fontFamily: Fonts.PoppinsBold,
  },
  clearListTxt: {
    fontSize: hp('1.6'),
    color: '#1ED18C',
    // justifyContent: 'center',
    // fontFamily: Fonts.PoppinsBold,
  },
  printTxt: {
    fontSize: hp('1.6'),
    color: '#1ED18C',
    // justifyContent: 'center',
    // fontFamily: Fonts.PoppinsBold,
  },
  applyTxt: {
    fontSize: hp('1.7'),
    color: '#1ED18C',
    // justifyContent: 'center',
    // fontFamily: Fonts.PoppinsBold,
  },

  //search realated
  searchBarStyle: {
    backgroundColor: 'white',
    elevation: 0,
    borderWidth: 1,
    borderColor: '#EEEEEE',
    height: hp('4.8'),
    borderRadius: 7,
    width: '100%',
    color: '#9C9C9C',
    '@media (max-width: 1600px) and (min-width: 450px)': {
      height: hp('4.8'),
      borderRadius: 7,
    },
    '@media (max-width: 450px)': {
      height: hp('5.5'),
    },
  },
  searchSection: {
    height: hp('7'),
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: wp('94'),
    alignSelf: 'center',
  },
  dropdownItem: {
    padding: 10,
    flex: 1,
    flexWrap: 'wrap',
    flexDirection: 'column',
    borderBottomWidth: 1,
    borderColor: '#e6e6e6',
  },
  dropdownItemText: {
    flex: 1,
    flexWrap: 'wrap',
    fontSize: wp('2'),
  },
  itemText: {
    fontSize: wp('1.6'),
    paddingTop: 5,
    paddingBottom: 5,
    margin: 2,
  },
  autocompleteContainer: {
    backgroundColor: '#e52',
    borderWidth: 0,
    marginLeft: 10,
    marginRight: 10,
    //paddingLeft: 15,
    zIndex: 5,
  },
  inputContainer: {
    //minWidth: 300,
    //width: "90%",
    //height: 55,
    height: hp('4'),
    backgroundColor: 'transparent',
    //color: '#6C6363',
    //fontSize: 18,
    //fontFamily: 'Roboto',
    zIndex: 3,
    //borderBottomColor: 'rgba(108, 99, 99, .7)',
    borderColor: 'transparent',
  },
  // autocompleteContainer: {
  //   flex: 1,
  //   left: 0,
  //   position: "absolute",
  //   right: 0,
  //   top: 0,
  //   zIndex: 3,
  //   padding: 5,
  // },
  autocomplete: {
    alignSelf: 'stretch',
    height: hp('50'),
    margin: 10,
    marginTop: 50,
    backgroundColor: '#FFF',
  },
  cell: {
    flex: 1,
    borderWidth: 1,
    borderColor: 'lightblue',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cellText: {
    flex: 1,
    marginLeft: 10,
  },

  pickerView: {
    borderWidth: 1,
    borderRadius: hp('1'),
    borderColor: '#EEEEEE',
    width: wp('15'),
    height: hp('4'),
    marginLeft: wp('5'),
    marginRight: wp('2'),
    '@media (max-width: 1600px) and (min-width: 450px)': {
      width: wp('16'),
      marginLeft: wp('1'),
    },
    '@media (max-width: 450px)': {
      width: wp('26'),
      marginLeft: wp('4'),
    },
  },
  pickerInside: {
    width: wp('15'),
    height: hp('4'),
    transform: [{scaleX: 1}, {scaleY: 1}],
    '@media (max-width: 1600px) and (min-width: 450px)': {
      width: wp('35'),
    },
    '@media (max-width: 450px)': {
      width: wp('24'),
      fontSize: 0.5,
    },
  },
  viewStyle: {
    flex: 1,
    alignSelf: 'center',
    flexDirection: 'row',
    width: wp('50'),
    marginRight: wp('2'),
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  itemStyle: {
    fontSize: hp('6'),
    // fontFamily: 'Roboto-Regular',
    color: '#007aff',
  },
  pickerStyle: {
    width: wp('10'),
    height: 40,
    color: '#007aff',
    fontSize: hp('3'),
    // fontFamily: 'Roboto-Regular',
  },
  textStyle: {
    fontSize: hp('2'),
    // fontFamily: 'Roboto-Regular',
  },
  dropdownsty: {
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 10,
    width: wp('14'),
    height: hp('4'),
    '@media (max-width: 1600px) and (min-width: 450px)': {
      fontSize: hp('1.4'),
      paddingTop: 10,
      paddingBottom: 10,
      paddingLeft: 10,
      width: wp('14'),
    },
    '@media (max-width: 450px)': {
      paddingTop: 12,
      paddingBottom: 0,
      width: wp('25'),
    },
  },

  //dropdown
  dropdownFont: {
    fontSize: 15,
    paddingTop: 10,
    paddingBottom: 10,
    height: hp('3.5'),
    color:"gray",
    '@media (max-width: 1600px) and (min-width: 450px)': {
      fontSize: hp('1.4'),
    },
    '@media (max-width: 450px)': {
      paddingTop: 3,
      paddingBottom: 5,
      fontSize: 12,
      height: hp('4'),
    },
  },
  dropdownIcon:{

    // '@media (max-width: 1600px) and (min-width: 450px)': {

    // },
    '@media (max-width: 450px)': {
      marginTop: -10,
    },
  },
  dropdownFontsel: {
    fontSize: 15,
    paddingTop: 10,
    paddingBottom: 10,
    color:"gray",
    '@media (max-width: 1600px) and (min-width: 450px)': {
      fontSize: hp('1.4'),
    },
    '@media (max-width: 450px)': {
      fontSize: 8,
    },
  },
  searchBarView: {
    width: '89%',
    top: 0,
    left: 0,
    position: 'absolute',
    '@media (max-width: 1600px) and (min-width: 450px)': {
      width: '89%',
    },
    '@media (max-width: 450px)': {
      width: '85%',
    },
  },

  barCodeBtn: {
    width: '10%',
    top: 0,
    right: 0,
    position: 'absolute',
    height: hp('4.8'),
    backgroundColor: '#1ED18C',
    borderRadius: wp('1'),
    alignItems: 'center',
    justifyContent: 'center',
    '@media (max-width: 1600px) and (min-width: 450px)': {
      height: hp('4.8'),
      width: '10%',
    },
    '@media (max-width: 450px)': {
      height: hp('5.5'),
      width: '13%',
      borderRadius: wp('1.5'),
    },
  },
  barcodeIcn: {
    height: hp('3'),
    resizeMode: 'contain',
    '@media (max-width: 1600px) and (min-width: 450px)': {
      height: hp('3'),
    },
    '@media (max-width: 450px)': {
      height: hp('3'),
    },
  },
});
