import {Dimensions} from 'react-native';

const React = require('react-native');
const {width: WIDTH, height: height} = Dimensions.get('window');
const {StyleSheet} = React;
import {Fonts} from '../utils/Fonts';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import * as colors from '../style/Common/ColorsStyle';


module.exports = StyleSheet.create({
  container: {
    flex: 1,
    // width: WIDTH,
    height: '100%',
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  // search view bar style start ----
  searchView: {
    width: '90%',
    height: hp('6'),
    paddingHorizontal:'0%',
    // marginHorizontal: '4%',
    // backgroundColor: 'red',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: hp('2'),
  },
  searchInput: {
    width: '90%',
    height: hp('5'),
    // backgroundColor: '#F6F6F6',
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  searchIcon: {
    width: 20,
    height: 20,
    marginLeft: '5%',
  },
  TxtInput: {
    width: '85%',
    height: hp('7'),
    fontSize: hp(2),
    fontWeight: 'bold',
    // backgroundColor: 'red',
  },
  filterBtn: {
    width: wp('11'),
    height: hp('5'),
    backgroundColor: colors.primaryColor,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
    
  },
  filterIcon: {
    width: 30,
    height: 20,
  },
  titleTxt: {
    fontSize: hp('2.2'),
    fontFamily: Fonts.PoppinsBold,
    color: 'black',
    fontWeight: 'bold',
    //textAlign: 'center',
  },
  titleView: {
    width: '90%',
    height: hp('5'),
    marginTop: hp('1'),
    justifyContent: 'flex-start',
  },
  // search view bar style end ----
  row: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 30,
    marginTop: 30,
    //padding:10,
  },
  box: {
    flex: 1,
    backgroundColor: 'white',
    height: hp('55'),
  
  },
  // box1: {
  //    backgroundColor: 'green',
     
  
  // },
  // box2: {
  //   backgroundColor: 'orange',

  // },
  CardDetail: {
    alignSelf: 'flex-start',
    alignItems: 'flex-start',
    flexDirection: 'row',
    position: 'absolute',
    justifyContent: 'flex-start',
    // backgroundColor: "#009387",
  },
  CardDetail1: {
    // alignSelf: 'center', 1ED18C
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.primaryColor,
    borderRadius: 20,
    marginHorizontal: 5,
    width: wp('25'),
  },
  CardDetail2: {
    fontFamily: Fonts.PoppinsMedium,
    // alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f6f6f6',
    borderRadius: 20,
    marginHorizontal: 5,
    width: wp('25'),
  },
  detailContent: {
    margin: 8,
    alignItems: 'center',
  },
  title: {
    fontSize: hp('1.5'),
    fontFamily: Fonts.PoppinsMedium,
    color: 'white',
    fontWeight: 'bold',
  },
  title1: {
    fontSize: hp('1.5'),
    fontFamily: Fonts.PoppinsMedium,
    color: '#979797',
    fontWeight: 'bold',
  },
  bodyView: {
    flexDirection: 'row',
    width: '95%',
    marginTop: '-1%',
    justifyContent: 'space-between',
    //marginLeft: '10%',
    // backgroundColor: 'red',
    //paddingRight: 10,
    //marginLeft: '5%',
    //paddingLeft: 10,
    //paddingHorizontal: 10,
    height: hp('4'),
  },
  flatlist: {
    //flexGrow: 0,
    //marginLeft:wp('-2'),
    //marginRight:wp('2'),
    width: '100%',
    //marginTop: wp('20%')
  },
  item2: {
    marginBottom: 10,
    width: wp('29'),
    height: hp('35'),
    borderRadius: 10,
    backgroundColor: 'white',
    alignItems: 'center',
    // alignItems: 'center',
    marginHorizontal: wp('1'),
    //paddingLeft: 5,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 1,
    margin: 5,
    // marginTop: hp('-2'),
    alignSelf: 'center',
  },
  cardMainTxtView1: {
    width: '100%',
    height: hp('15'),
    justifyContent: 'center',
    //marginLeft:wp('2'),
    // marginTop:hp('-1%'),
    // backgroundColor:'black'
  },
  cardSubTxtView2: {
    marginTop: wp('-1'),
    width: '100%',
    height: wp('4'),
    // backgroundColor:'blue'
  },
  itemImage: {
    width: '100%',
    height: '100%',
    borderRadius: 10,

    //padding: 3,
    //borderRadius: 10,
    // left: '8%',
  },
  cardSubTxtView: {
    width: '95%',
    height: hp('5'),
    alignItems: 'flex-start',
    justifyContent: 'center'
    // width: '100%',
    // //height: 'auto',
    // // paddingTop: 5,
    // // paddingBottom: 5,
    // //backgroundColor: 'yellow',
    // //borderRadius: 10,
    // //marginTop: '-%',
    // alignItems: 'flex-start',
    // justifyContent: 'center',
  },
  cardSubMainTxt: {
    fontSize: hp('1.5'),
    fontFamily: Fonts.PoppinsRegular,
    color: colors.primaryColor,
    fontWeight: 'bold',
    marginLeft: wp('1'),
   
  },
  cardSubTxt: {
    fontSize: hp('1.5'),
    fontFamily: Fonts.PoppinsSemiBold,
    color: 'gray',
    marginLeft: '2%',
  },
  cardSubTxtView4: {
    marginTop: wp('-0.4'),
    width: '100%',
    height: wp('3.5'),
    flexDirection: 'row',
    // backgroundColor: 'yellow',
  },
  packtxt: {
    fontSize: hp('1.5'),
    fontFamily: Fonts.PoppinsSemiBold,
    color: 'gray',
    marginLeft: wp('0.8'),
    marginTop: wp('-0.2'),
  },
  cardSubTxtView3: {
    marginTop: wp('1'),
    width: '100%',
    height: wp('3'),
    //backgroundColor: 'red',
  },
  cardSubTxtView5: {
    marginTop: wp('-0.4%'),
    width: '100%',
    height: wp('3'),
    flexDirection: 'row',
    // backgroundColor:"blue"
  },
  stocktxt: {
    fontSize: hp('1.5'),
    fontFamily: Fonts.PoppinsSemiBold,
    color: 'gray',
    marginLeft: wp('0.8'),
  },
  priceTxt: {
    fontSize: hp('1.5'),
    color: 'black',
    fontFamily: Fonts.PoppinsSemiBold,
    marginLeft: wp('1'),
    fontWeight: 'bold',
  },
  cart: {
    width: wp('9'),
    height: wp('5'),
    // backgroundColor:colors.primaryColor,
    borderColor: colors.primaryColor,
    borderWidth: wp('0.2'),
    borderRadius: 8,
    marginLeft: wp('19'),
    marginTop: wp('-4'),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  cartIcon: {
    marginLeft: '12%',
  },
  cartText: {
    color: colors.primaryColor,
    fontFamily: Fonts.PoppinsRegular,
    paddingStart: wp('1'),
    fontSize: hp('1.5'),
    marginLeft: wp('1'),
  },
  cardSubTxt1: {
    fontSize: hp('1.5'),
    fontFamily: Fonts.PoppinsRegular,
    color: 'black',
    marginLeft: '-0.8%',
  },
  cardSubTxt2: {
    fontSize: hp('1.5'),
    fontFamily: Fonts.PoppinsRegular,
    color: colors.primaryColor,
    marginLeft: '1%',
  },
  mainImage: {
    marginBottom: 5,
    width: wp('43'),
    height: hp('37'),
    borderRadius: 10,
    backgroundColor: 'white',
    alignItems: 'center',
    // alignItems: 'center',
    marginHorizontal: wp('1'),
    margin: 5,
    // marginTop: hp('-2'),
    alignSelf: 'center',
  },
  showBox: {
    marginBottom: 10,
    width: wp('43'),
    height: hp('15'),
    borderRadius: 10,
    backgroundColor: 'white',
    alignItems: 'center',
    marginHorizontal: wp('1'),
    margin: 5,
    marginTop: hp('1'),
    alignSelf: 'center',
  },
  listView: {
    marginBottom: 5,
    width: wp('45%'),
    borderRadius: 20,
    backgroundColor: '#FCFBFB',
    alignItems: 'center',
    // alignItems: 'center',
    //paddingLeft: 5,
    // shadowOffset: {width: 0, height: 2},
    // shadowOpacity: 0.6,
    // shadowRadius: 1,
    // elevation: 2,
    // marginTop: hp('-2'),
    alignSelf: 'center',
  },
  imageView: {
    width: '90%',
    height: '60%',
    alignItems: 'center',
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 1,
  },
  detailBox: {
    width: '90%',
    height: hp('15'),
    justifyContent: 'center',
    borderRadius: 10,
  },
  // ---- main image inside details styles-----
  insideBox: {
    width: '100%',
    height: hp('20'),
    justifyContent: 'center',
  },
  titleView: {
    width: '100%',
    height:'auto',
    //height: hp('3.8'),
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  titleTxt: {
    fontSize: hp('1.6'),
    marginLeft:wp('1'),
    fontFamily: Fonts.PoppinsRegular,
    color: '#090909',
    fontWeight: 'bold',
  },
  subView: {
    marginTop: wp('-1'),
    width: '100%',
    height: wp('4'),
    // backgroundColor:'blue' ,
    flexDirection: 'row',
  },
  subTxt: {
    fontSize: hp('1.5'),
    fontFamily: Fonts.PoppinsSemiBold,
    color: colors.primaryColor,
    marginLeft: '1%',
  },
  packtxt2: {
    fontSize: hp('1.5'),
    fontFamily: Fonts.PoppinsRegular,
    color: 'gray',
    marginLeft: wp('0.8'),
    marginTop: wp('-0.2'),
  },
  sizeTxt: {
    fontSize: hp('1.5'),
    fontFamily: Fonts.PoppinsRegular,
    color: colors.primaryColor,
    marginLeft: '2%',
  },
  productNum: {
    fontSize: hp('1.5'),
    fontFamily: Fonts.PoppinsRegular,
    color: 'gray',
    marginLeft: wp('0.8'),
    marginTop: wp('-0.2'),
  },
  sizeView: {
    marginTop: wp('-0.4'),
    width: '100%',
    height: wp('3.5'),
    flexDirection: 'row',
    // backgroundColor: 'yellow',
  },
  stockView: {
    marginTop: wp('-0.4'),
    width: '100%',
    height: wp('3'),
    flexDirection: 'row',
    // backgroundColor:"blue"
  },
  stocktxt2: {
    fontSize: hp('1.5'),
    fontFamily: Fonts.PoppinsSemiBold,
    color: 'gray',
    marginLeft: wp('0.8'),
  },
  storeTxt: {
    fontSize: hp('1.5'),
    fontFamily: Fonts.PoppinsRegular,
    color: '#138B13',
    marginLeft: '1%',
  },

  showBox2: {
    marginBottom: 10,
    width: wp('43'),
    height: hp('6'),
    borderRadius: 10,
    //backgroundColor: 'pink',
    alignItems: 'center',
    // alignItems: 'center',
    marginHorizontal: wp('1'),
    margin: 5,
    marginTop: hp('-1'),
    alignSelf: 'center',
  },
  showBox3: {
    marginBottom: 10,
    width: wp('43'),
    height: hp('9'),
    borderRadius: 10,
    backgroundColor: 'white',
    alignItems: 'center',
    // alignItems: 'center',
    marginHorizontal: wp('1'),
    padding: 10,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 1,
    margin: 5,
    marginTop: hp('-1'),
    alignSelf: 'center',
  },
  calImg: {
    // height: hp('17%'),
    marginTop: '2%',
    // marginBottom:'5%'
  },
  showBoxView1: {
    width: '100%',
    height: hp('3'),
    alignItems: 'flex-start',
    justifyContent: 'center',
    marginLeft: hp('2'),
    //backgroundColor:"blue"
  },
  showBoxView2: {
    width: '100%',
    height: hp('2.6'),
    alignItems: 'flex-end',
    justifyContent: 'center',
    marginLeft: hp('6'),
    // backgroundColor:"yellow" ,
    flexDirection: 'row',
  },
  topicTxt: {
    fontSize: hp('1.7'),
    fontFamily: Fonts.PoppinsMedium,
    color: colors.primaryColor,
    marginLeft: '2%',
  },
  text1: {
    fontSize: hp('1.5'),
    fontFamily: Fonts.PoppinsRegular,
    color: 'gray',
    marginTop: hp('-4'),
    marginLeft: '2%',
  },
  recImg: {
    marginLeft: '2%',
    marginBottom: '2%',
  },
  // ---- list view ---------
  mainListView: {
    width: '100%',
    height: hp('52.5'),
    borderRadius: 10,
    //backgroundColor:'lightblue',
  },
  topicBox: {
    marginTop: hp('1'),
    marginLeft: wp('1'),
  },
  rowView1: {
    marginTop: wp('1'),
    width: '100%',
    height: wp('4.8'),
    flexDirection: 'row',
  },
  rowTxt1: {
    fontSize: hp('1.4'),
    fontFamily: Fonts.PoppinsRegular,
    color: 'gray',
    marginLeft: wp('1.5'),
    justifyContent: 'center',
    width:'22%',
  },
  rowTxt2: {
    fontSize: hp('1.4'),
    fontFamily: Fonts.PoppinsRegular,
    color: 'gray',
    marginLeft: wp('1'),
    width:'22%',
  },
  rowTxt3: {
    fontSize: hp('1.4'),
    fontFamily: Fonts.PoppinsRegular,
    color: 'gray',
    marginLeft: wp('1'),
    width:'7%',
  },
  rowTxt4: {
    fontSize: hp('1.4'),
    fontFamily: Fonts.PoppinsRegular,
    color: colors.primaryColor,
    marginLeft: wp('1.5'),
    width:'23%',
  },
  qtyInput: {
    width: wp('10'),
    height: hp('4'),
    fontSize: hp(1.5),
    marginLeft: wp('1'),
    marginTop: hp('-1'),
    borderRadius: 12,
    borderWidth: hp('0.2'),
    borderColor: '#ECE7E7',
    backgroundColor: 'white',
    textAlign: 'center',
  },
  rowView2: {
    width: '100%',
    height: wp('7'),
    marginTop:hp('2'),
   // backgroundColor: 'white',
   backgroundColor:'#FCFBFB' ,
    flexDirection: 'row',
  },
  AddBtn: {
    width: wp('22'),
    height: hp('4'),
    backgroundColor: colors.primaryColor,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: '18%',
    marginRight: '2%',
  },
  addBtn1: {
    fontSize: hp('1.6'),
    fontFamily: Fonts.PoppinsMedium,
    color: 'white',
    alignItems: 'center',
  },
  total: {
    width: '41%',
    height: wp('6'),
    flexDirection: 'column',
    marginTop:hp('-0.5'),
  },
  totalColum1: {
    width: '100%',
    height: wp('3'),
    //backgroundColor:'pink' ,
  },
  totalColum2: {
    width: '100%',
    height: wp('3'),
    //backgroundColor:'green' ,
  },
  addTxt1: {
    fontSize: hp('1.8'),
    fontFamily: Fonts.PoppinsSemiBold,
    color: 'black',
    alignItems: 'center',
    fontWeight: 'bold',
    marginLeft: wp('4'),
  },
  addTotal: {
    fontSize: hp('1.8'),
    fontFamily: Fonts.PoppinsSemiBold,
    color: colors.primaryColor,
    // alignItems: 'baseline',
    alignItems: 'center',
    fontWeight: 'bold',
    marginLeft: wp('6'),
  },
  //----- 100g-----
  rowTxt22: {
    fontSize: hp('1.7'),
    fontFamily: Fonts.PoppinsRegular,
    color: 'gray',
    marginLeft: wp('3.1'),
  },
  rowTxt23: {
    fontSize: hp('1.7'),
    fontFamily: Fonts.PoppinsRegular,
    color: 'gray',
    marginLeft: wp('4.5'),
  },
  //----- calander box -----
  calBox1: {
    width: wp('43'),
    height: hp('2.5'),
    marginTop: hp('1.6'),
  },
  calBox2: {
    width: wp('43'),
    height: hp('1'),
    marginTop: hp('-1'),
  },
  calBox3: {
    width: wp('43'),
    height: hp('1'),
    marginTop: hp('0.5'),
  },
  calBox4: {
    width: wp('43'),
    height: hp('1'),
    marginTop: hp('0.5'),
  },
  calBox5: {
    width: wp('43'),
    height: hp('1'),
    marginTop: hp('1.5'),
  },
  rowCal: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  boxCal: {
    flex: 1,
    height: hp('2.5'),
    marginTop:hp('-1.7'),

  },
  boxCal1: {
    flex: 1,
    backgroundColor: '#EFFFF9',
    height: hp('2.5'),
    marginTop:hp('-1.7'),
  },
  month1: {
    fontSize: hp('1.4'),
    fontFamily: Fonts.PoppinsMedium,
    color: 'gray',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: wp('1'),
  },
  month2: {
    fontSize: hp('1.4'),
    fontFamily: Fonts.PoppinsMedium,
    color: colors.primaryColor,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: wp('1'),
  },
  //------ sow row
  rowSow: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',

  },
  sowBox: {
    flex: 1,
    height: hp('1'),
  },
  sow: {
    backgroundColor: '#FBD7F9',
    height: hp('1'),
    borderColor: '#F6AFF2',
    borderWidth: hp('0.2'),
  },
  // ------ plant row -------
  rowPlant: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  plantBox: {
    flex: 1,
    height: hp('1'),
  },
  plant: {
    backgroundColor: '#D5FDFE',
    height: hp('1'),
    borderColor: '#A3FDFE',
    borderWidth: hp('0.2'),
  },
  //------ harves row----- 
  rowHarves:{
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between', 
  },
  harvesBox: {
    flex: 1,
    height: hp('1'),
  },
  harves: {
    backgroundColor: '#FCF2DA',
    height: hp('1'),
    borderColor: '#FCDA8B',
    borderWidth: hp('0.2%'),
  },
  notes: {
    backgroundColor: '#AAF0D1',
    height: hp('1'),
    borderColor: '#66CDAA',
    borderWidth: hp('0.2%'),
  },
  backBtn:{
    width: wp('13'),
    height: hp('4'),
    borderColor:colors.primaryColor,
    borderWidth:wp('0.2'),
    borderRadius: 5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  backText:{
    color:colors.primaryColor,
    fontFamily: Fonts.PoppinsRegular,
    paddingStart:wp('1'),
    fontSize:hp('1.8'),
  },
  backIcon:{
    marginLeft: '12%',
  },
  backView:{
    width: wp('40'),
    height: hp('5'), 
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginTop: hp('1'),
    alignSelf:'flex-start',
    marginLeft:wp('3')
  },
  relatedView:{
    height: 'auto',
    width:'100%',
    marginTop:hp('1'),
    alignSelf:'flex-start',
  },
  relatedView2:{
    height: 'auto',
    width:'100%',
    marginTop:hp('1'),
    alignSelf:'flex-start',
  },
  emptyListStyle:{
    padding: 10,
    textAlign: 'center',
    fontSize: hp('1.5'),
    fontFamily: Fonts.PoppinsMedium,
    color: '#979797',
  }
});
